EP3/config/routes.rb
Rails.application.routes.draw do
  resources :tarefas
  devise_for :users, controllers: { registrations: "registrations"}
  root 'home#index'
  get 'login' => 'home#login'
  get 'tarefa', to:'home#tarefa'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

EP3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

EP3/app/models/tarefa.rb
class Tarefa < ApplicationRecord
	validates_presence_of :title, :content
	
end

EP3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

EP3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

EP3/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end

  def login
  	
  end
  def tarefa
  	if user_signed_in?
  		redirect_to tarefas_path
  	else
  		redirect_to new_user_session_path	
  	end
  end
end

EP3/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
	
	def account_update_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	end
end	

EP3/app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy]

  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.all
  end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: 'Tarefa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarefa_params
      params.require(:tarefa).permit(:title, :content)
    end
end

EP3/app/helpers/application_helper.rb
module ApplicationHelper
end

EP3/app/helpers/home_helper.rb
module HomeHelper
end

EP3/app/helpers/tarefas_helper.rb
module TarefasHelper
end

EP3/app/views/home/index.html.erb
<html>
    <header>
       <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Agenda Pessoal</h1>
                <hr>
                <p>Organize seus compromissos e tarefas!</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Descubra mais</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Sobre</h2>
                    <hr class="light">
                    <p class="text-faded">Organize suas tarefas de forma simples e organizada!</p>
                    <a href="#services" class="page-scroll btn btn-default btn-xl sr-button">Comece já!</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Funcionalidades</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
                        <h3>Atividades</h3>
                        <p class="text-muted">Registre suas tarefas de forma simples e rápida!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
                        <h3>Cadastro</h3>
                        <p class="text-muted">Rápido e fácil, sem nenhuma complicação.</p>
                    </div>
                </div>     
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Entre já!</h2>
                <%= link_to "Login", new_user_session_path, :class => 'btn btn-default btn-xl sr-button'  %> 
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Contatos</h2>
                    <hr class="primary">
                    <p>Algum problema? Alguma dúvida? Sugestão? Fale com a gente!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact "></i>
                    <p>feedback@startbootstrap.com</p>
                </div>
                <div class="col-lg-4 text-center"><div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact "></i>
                    <p>gabrielademoraes10@gmail.com</p>
                </div>
            </div>
        </div>
    </section>
</html>

EP3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda Pessoal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Theme CSS -->
      <link href="https://blackrockdigital.github.io/startbootstrap-creative/css/creative.min.css" rel="stylesheet">
  </head>

  <body>
  
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Agenda Pessoal</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <% if user_signed_in? %>
                        <p><font color = white>Olá, <%= current_user.email %></font></p>
                      <% end %>
                    </li>
                    <li>
                      <% if user_signed_in? %>
                        <%= link_to "Tarefas", tarefas_path, :class => 'navbar-link'  %>
                      <% end %>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">Sobre</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Funcionalidades</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contato</a>
                    </li>
                    <li>
                      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> 
                    <li>
                        <%= link_to "Sair", destroy_user_session_path, :method => 'delete', :class=>'navbar-link'%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->

     </div>
        <!-- /.container-fluid -->
   </nav>
    
    <%= yield %>
    <footer>
        <div class="container text-center">
            <p>&copy; 2017 Company, Inc.</p>
        </div>
    </footer>

  </body>
</html>

EP3/app/views/tarefas/_form.html.erb
<%= form_with(model: tarefa, local: true) do |form| %>
  <% if tarefa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
      <% tarefa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :tarefa_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :tarefa_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

EP3/app/views/tarefas/edit.html.erb
<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Agenda Pessoal</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <% if user_signed_in? %>
                        <p><font color = white>Hello, <%= current_user.email %></font></p>
                      <% end %>
                    </li>
                    <li>
                        <%= link_to "Sair", destroy_user_session_path, :method => 'delete', :class=>'navbar-link'%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->

     </div>
        <!-- /.container-fluid -->
   </nav>
<p style="line-height: 4em"><br></p> 
<div class="jumbotron">
	<div class="container">  
		<h1>Edite sua Tarefa</h1>
    <p style="line-height: 2em"><br></p> 
		<%= render 'form', tarefa: @tarefa %>

		<%= link_to 'Editar', @tarefa,:class=>"btn btn-info" %> |
		<%= link_to 'Voltar', tarefas_path,:class=>"btn btn-info" %>
	</div>
</div>

EP3/app/views/tarefas/index.html.erb
<p id="notice"><%= notice %></p>

<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Agenda Pessoal</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <% if user_signed_in? %>
                        <p><font color = white>Olá, <%= current_user.email %></font></p>
                      <% end %>
                    </li>
                    <li>
                        <%= link_to "Sair", destroy_user_session_path, :method => 'delete', :class=>'navbar-link'%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->

     </div>
        <!-- /.container-fluid -->
   </nav>

<p style="line-height: 2em"><br></p>
<div class="jumbotron">
  <div class="container">
    <h1>Suas Tarefas</h1>
    <p style="line-height: 2em"><br></p>
    <style>
      table{
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width:80%;
      }
      td, th{
        border: 4px solid #87CEEB;
        text-align: left;
        padding: 5px;
      }
      tr:nth-child(even){
        background-color: #ADD8E6;
      }
    
    </style>  
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tarefas.each do |tarefa| %>
          <tr>
            <td><%= tarefa.title %></td>
            <td><%= tarefa.content %></td>
            <td><%= link_to 'Detalhes', tarefa ,:class=>"btn btn-g btn-success"%></td>
            <td><%= link_to 'Editar', edit_tarefa_path(tarefa),:class=>"btn btn-g btn-warning" %></td>
            <td><%= link_to 'Cumprida!', tarefa, method: :delete, data: { confirm: 'Essa tarefa foi cumprida?' },:class=>"btn btn-g btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>

<%= link_to 'Nova Tarefa', new_tarefa_path,:class=>"btn btn-info"%>
</div>

EP3/app/views/tarefas/new.html.erb
<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Agenda Pessoal</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <% if user_signed_in? %>
                        <p><div class = "navbar-brand"><font color = white>Olá <%= current_user.email %></font></p>
                      <% end %>
                    </li>
                    <li>
                        <%= link_to "Sair", destroy_user_session_path, :method => 'delete', :class=>'navbar-link'%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->

     </div>
        <!-- /.container-fluid -->
   </nav>
<p style="line-height: 4em"><br></p>
<div class="jumbotron">
	<div class="container">
		<h1>Nova Tarefa</h1>
    <p style="line-height: 2em"><br></p>
		<%= render 'form', tarefa: @tarefa %>

		<%= link_to 'Voltar', tarefas_path,:class=>"btn btn-info" %>
	</div>
</div>

EP3/app/views/tarefas/show.html.erb
<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Agenda Pessoal</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <% if user_signed_in? %>
                        <p><font color = white>Hello, <%= current_user.email %></font></p>
                      <% end %>
                    </li>
                    <li>
                        <%= link_to "Sair", destroy_user_session_path, :method => 'delete', :class=>'navbar-link'%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->

     </div>
        <!-- /.container-fluid -->
   </nav>
<p style="line-height: 4em"><br></p>
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <div class="container">
	<p>
  		<strong>Title:</strong>
  		<%= @tarefa.title %>
	</p>

	<p>
  		<strong>Content:</strong>
  		<%= @tarefa.content %>
	</p>
	<%= link_to 'Editar', edit_tarefa_path(@tarefa),:class=>"btn btn-info" %> |
	<%= link_to 'Voltar', tarefas_path, :class=>"btn btn-info"%>
	</div>
</div>